title: Page
icon: document
options:
  changeSlug: true
  changeStatus: true
  changeTemplate: true
  changeTitle: true
  delete: true
  duplicate: true
  preview: true
  read: true
  update: true

tabs:
  #
  #  Content Tab
  #
  content:
    label: Content
    columns:
      - width: 1/3
        sections:
          #
          #  Files
          #
          files:
            type: files
            image:
              back: black
              cover: true

      - width: 2/3
        sections:
          content:
            type: fields
            fields:
              #
              #  Text
              #
              text:
                label: Text
                type: textarea
                size: medium
                buttons:
                  - bold
                  - italic
                  - link
                  - email
                  - ul
                  - ol

  #
  #  SEO Tab
  #
  seo:
    extends: tabs/seo
